# Generated by UmaDev — multi-stage Node build.
# Production hardening:
# - Pin the base image to a digest for reproducibility:
#     docker build --build-arg NODE_BASE=node:20-alpine@sha256:<digest> .
# - Or override the base entirely (e.g. a hardened internal image):
#     docker build --build-arg NODE_BASE=registry.internal/node:20-hardened .
# UmaDev emits the mutable tag as the default so the scaffold builds
# out-of-the-box; set NODE_BASE at build time to pin/override.
ARG NODE_BASE=node:20-alpine
FROM ${NODE_BASE} AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev || npm install --omit=dev

FROM ${NODE_BASE} AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build --if-present

FROM ${NODE_BASE} AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup -S app && adduser -S app -G app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/public ./public
COPY --from=builder /app/src ./src
RUN chown -R app:app /app
USER app
HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1
EXPOSE 3000
CMD ["npm", "start"]
