import type { CurrentCapabilities } from './sessionApi';
import { translate } from '../../shared/i18n/messages';
import { peopleImportCapabilities } from '../../shared/security/peopleImportCapabilities';

export function getDemoSession(): CurrentCapabilities {
  return {
    capabilities: [
      'ATTENDANCE_DASHBOARD:READ',
      'ATTENDANCE_REPORT:READ',
      'ATTENDANCE_REPORT:EXPORT_CREATE',
      'ATTENDANCE_REPORT:EXPORT_DOWNLOAD',
      'ATTENDANCE_SELF:READ',
      'LEAVE_SELF:READ',
      'ATTENDANCE_FEEDBACK:READ',
      'ATTENDANCE_FEEDBACK:CREATE',
      'POLICY:READ',
      'POLICY:CREATE',
      'POLICY:EDIT',
      'POLICY:VALIDATE',
      'POLICY:SIMULATE',
      'POLICY:PUBLISH',
      'POLICY:DEACTIVATE',
      'POLICY:ROLLBACK',
      'ACCOUNT:READ',
      'ACCOUNT:CREATE',
      'ACCOUNT:EDIT',
      'ACCOUNT:LOCK',
      'ACCOUNT:UNLOCK',
      'ACCOUNT:RESET_PASSWORD',
      'ROLE:READ',
      'ROLE:ASSIGN',
      'AUDIT:READ',
      'MASTER_DATA:READ',
      'PEOPLE_IMPORT:TEMPLATE_DOWNLOAD',
      'PEOPLE_IMPORT:READ',
      'PEOPLE_IMPORT:CREATE',
      peopleImportCapabilities.submitFile,
      'PEOPLE_IMPORT:MAP',
      'PEOPLE_IMPORT:PRECHECK',
      peopleImportCapabilities.downloadErrorReport,
      'PEOPLE_IMPORT:PUBLISH',
      'PEOPLE_IMPORT:VOID',
      'PEOPLE_IMPORT:ROLLBACK',
      'ORGANIZATION:READ',
      'ORGANIZATION:CREATE',
      'ORGANIZATION:EDIT',
      'EMPLOYEE:READ',
      'EMPLOYEE:CREATE',
      'EMPLOYEE:EDIT',
      'EMPLOYMENT:READ',
      'EMPLOYMENT:CREATE',
      'EMPLOYMENT:EDIT',
      'PRIOR_SERVICE:READ',
      'PRIOR_SERVICE:ADJUST',
      'ATTENDANCE_SETUP:READ',
      'ATTENDANCE_SETUP:MANAGE_GROUP',
      'ATTENDANCE_SETUP:ASSIGN',
      'ATTENDANCE_SETUP:MANAGE_SHIFT',
      'ATTENDANCE_SETUP:MANAGE_CALENDAR',
      'ATTENDANCE_SETUP:MANAGE_POLICY',
      'ATTENDANCE_SOURCE:READ',
      'ATTENDANCE_SOURCE:CONFIGURE',
      'ATTENDANCE_SOURCE:RUN',
      'ATTENDANCE_SOURCE:RETRY',
      'ATTENDANCE_SOURCE:QUARANTINE_READ',
      'ATTENDANCE_PUNCH_IMPORT:READ',
      'ATTENDANCE_PUNCH_IMPORT:TEMPLATE_DOWNLOAD',
      'ATTENDANCE_PUNCH_IMPORT:UPLOAD',
      'ATTENDANCE_PUNCH_IMPORT:PRECHECK',
      'ATTENDANCE_PUNCH_IMPORT:PUBLISH',
      'ATTENDANCE_PUNCH_IMPORT:PARTIAL_PUBLISH',
      'ATTENDANCE_PUNCH_IMPORT:VOID_OR_REVERSE',
      'ATTENDANCE_PUNCH_IMPORT:RAW_FILE_READ',
      'ATTENDANCE_PUNCH_IMPORT:RAW_ROW_READ',
      'ATTENDANCE_PUNCH_IMPORT:ERROR_REPORT_DOWNLOAD',
      'ATTENDANCE_PUNCH_IMPORT:DUPLICATE_REVIEW',
      'ATTENDANCE_PUNCH_IMPORT:RECALCULATE',
    ],
    menu: [
      { key: 'workbench', label: '考勤工作台', path: '/workbench' },
      { key: 'attendance-screen', label: '考勤大屏', path: '/attendance/screen' },
      { key: 'attendance-reports', label: '统计报表', path: '/attendance/reports' },
      { key: 'self-today', label: '今日状态', path: '/me/today' },
      { key: 'self-records', label: '我的考勤', path: '/me/records' },
      { key: 'self-leave', label: '我的假期', path: '/me/leave' },
      { key: 'self-feedback', label: '反馈中心', path: '/me/feedback' },
      { key: 'rules', label: '规则设置', path: '/rules' },
      { key: 'rule-templates', label: translate('rules.templates'), path: '/rules/templates' },
      { key: 'accounts', label: translate('access.accounts'), path: '/access/accounts' },
      { key: 'roles', label: translate('access.roles'), path: '/access/roles' },
      { key: 'audit', label: '操作记录', path: '/access/audit' },
      { key: 'people-import', label: '导入人员', path: '/people/import' },
      { key: 'organization', label: '部门与组织', path: '/people/organization' },
      { key: 'employees', label: '员工', path: '/people/employees' },
      { key: 'attendance-groups', label: '考勤组', path: '/rules/attendance-groups' },
      { key: 'attendance-shifts', label: '班次', path: '/rules/shifts' },
      { key: 'attendance-calendars', label: translate('attendanceSetup.calendars'), path: '/rules/calendars' },
      { key: 'attendance-policies', label: '考勤规则', path: '/rules/attendance-policy' },
      { key: 'attendance-sources-online', label: '考勤机数据', path: '/sources/online' },
      { key: 'attendance-sources-oa', label: 'OA 单据', path: '/sources/oa' },
      { key: 'attendance-source-jobs', label: '同步记录', path: '/sources/jobs' },
      { key: 'attendance-punch-imports', label: '导入打卡文件', path: '/sources/attendance-excel' },
    ],
  };
}
