import type { CurrentCapabilities } from './sessionApi';
import { translate } from '../../shared/i18n/messages';
import { peopleImportCapabilities } from '../../shared/security/peopleImportCapabilities';

export function getDemoSession(): CurrentCapabilities {
  return {
    capabilities: [
      'POLICY:READ',
      'POLICY:CREATE',
      'POLICY:EDIT',
      'POLICY:VALIDATE',
      'POLICY:SIMULATE',
      'POLICY:PUBLISH',
      'POLICY:DEACTIVATE',
      'POLICY:ROLLBACK',
      'ACCOUNT:READ',
      'ACCOUNT:CREATE',
      'ACCOUNT:EDIT',
      'ACCOUNT:LOCK',
      'ACCOUNT:UNLOCK',
      'ACCOUNT:RESET_PASSWORD',
      'ROLE:READ',
      'ROLE:ASSIGN',
      'AUDIT:READ',
      'MASTER_DATA:READ',
      'PEOPLE_IMPORT:TEMPLATE_DOWNLOAD',
      'PEOPLE_IMPORT:READ',
      'PEOPLE_IMPORT:CREATE',
      peopleImportCapabilities.submitFile,
      'PEOPLE_IMPORT:MAP',
      'PEOPLE_IMPORT:PRECHECK',
      peopleImportCapabilities.downloadErrorReport,
      'PEOPLE_IMPORT:PUBLISH',
      'PEOPLE_IMPORT:VOID',
      'PEOPLE_IMPORT:ROLLBACK',
      'ORGANIZATION:READ',
      'ORGANIZATION:CREATE',
      'ORGANIZATION:EDIT',
      'EMPLOYEE:READ',
      'EMPLOYEE:CREATE',
      'EMPLOYEE:EDIT',
      'EMPLOYMENT:READ',
      'EMPLOYMENT:CREATE',
      'EMPLOYMENT:EDIT',
      'PRIOR_SERVICE:READ',
      'PRIOR_SERVICE:ADJUST',
      'ATTENDANCE_SETUP:READ',
      'ATTENDANCE_SETUP:MANAGE_GROUP',
      'ATTENDANCE_SETUP:ASSIGN',
      'ATTENDANCE_SETUP:MANAGE_SHIFT',
      'ATTENDANCE_SETUP:MANAGE_CALENDAR',
      'ATTENDANCE_SETUP:MANAGE_POLICY',
    ],
    menu: [
      { key: 'rules', label: translate('rules.title'), path: '/rules' },
      { key: 'rule-templates', label: translate('rules.templates'), path: '/rules/templates' },
      { key: 'accounts', label: translate('access.accounts'), path: '/access/accounts' },
      { key: 'roles', label: translate('access.roles'), path: '/access/roles' },
      { key: 'audit', label: translate('access.audit'), path: '/access/audit' },
      { key: 'people-import', label: translate('peopleImport.title'), path: '/people/import' },
      { key: 'organization', label: translate('organization.title'), path: '/people/organization' },
      { key: 'employees', label: translate('employee.title'), path: '/people/employees' },
      { key: 'attendance-groups', label: translate('attendanceSetup.groups'), path: '/rules/attendance-groups' },
      { key: 'attendance-shifts', label: translate('attendanceSetup.shifts'), path: '/rules/shifts' },
      { key: 'attendance-calendars', label: translate('attendanceSetup.calendars'), path: '/rules/calendars' },
      { key: 'attendance-policies', label: translate('attendanceSetup.policy'), path: '/rules/attendance-policy' },
    ],
  };
}
