import type {
  AttendanceSourceJobView,
  AttendanceSourceView,
  IntegrationStatusView,
  OaDocumentView,
} from './attendanceSourceTypes';

export const demoAttendanceSources: AttendanceSourceView[] = [
  {
    sourceId: 'SRC-DELI-HQ-01',
    companyId: 'LEGAL-JIANGSU',
    sourceType: 'DELI_CLOUD',
    code: 'DELI_HQ_01',
    displayName: '总部得力考勤设备',
    state: 'ACTIVE',
    timeZone: 'Asia/Shanghai',
    configurationRevision: 3,
    committedWatermark: 'page-20260728-018',
    lastSuccessfulSyncAt: '2026-07-28T01:10:00Z',
    lastFailedSyncAt: null,
    lastFailureReason: null,
    rowVersion: 3,
  },
  {
    sourceId: 'SRC-OA-HQ-01',
    companyId: 'LEGAL-JIANGSU',
    sourceType: 'OA_ATTENDANCE',
    code: 'OA_HQ_01',
    displayName: '致远办公系统考勤单据',
    state: 'ACTIVE',
    timeZone: 'Asia/Shanghai',
    configurationRevision: 2,
    committedWatermark: 'document-version-0007',
    lastSuccessfulSyncAt: '2026-07-28T01:20:00Z',
    lastFailedSyncAt: null,
    lastFailureReason: null,
    rowVersion: 2,
  },
];

export const demoSourceJobs: AttendanceSourceJobView[] = [
  {
    jobId: 'JOB-20260728-001',
    sourceId: 'SRC-DELI-HQ-01',
    sourceDisplayName: '总部得力考勤设备',
    sourceType: 'DELI_CLOUD',
    state: 'SUCCEEDED',
    committedPages: 4,
    rawFactCount: 128,
    quarantinedCount: 0,
    safeErrorSummary: null,
    startedAt: '2026-07-28T01:00:00Z',
    completedAt: '2026-07-28T01:10:00Z',
    rowVersion: 1,
  },
  {
    jobId: 'JOB-20260728-002',
    sourceId: 'SRC-OA-HQ-01',
    sourceDisplayName: '致远办公系统考勤单据',
    sourceType: 'OA_ATTENDANCE',
    state: 'PARTIALLY_QUARANTINED',
    committedPages: 2,
    rawFactCount: 12,
    quarantinedCount: 1,
    safeErrorSummary: '1 条未识别状态已隔离；未暴露原始载荷',
    startedAt: '2026-07-28T01:15:00Z',
    completedAt: '2026-07-28T01:20:00Z',
    rowVersion: 2,
  },
];

export const demoOaDocuments: OaDocumentView[] = [
  {
    documentId: 'OA-DOC-DEMO-001',
    sourceDocumentId: '922337203685477580812346',
    sourceVersion: '7',
    documentType: 'LEAVE',
    sourceStatus: 'APPROVED',
    effectiveCandidate: true,
    employeeNumber: 'SZ1001',
    employeeName: '演示员工',
    department: '制造中心',
    leaveType: 'ANNUAL',
    overtimeTreatment: 'NOT_APPLICABLE',
    payrollCreditMinutes: 0,
    timeOffCreditMinutes: 0,
    recognizedWorkMinutes: 480,
    intervalStart: '2026-07-28T01:00:00Z',
    intervalEndExclusive: '2026-07-28T09:00:00Z',
  },
  {
    documentId: 'OA-DOC-DEMO-003',
    sourceDocumentId: '922337203685477580812348',
    sourceVersion: '1',
    documentType: 'OUTING',
    sourceStatus: 'APPROVED',
    effectiveCandidate: true,
    employeeNumber: 'SZ1002',
    employeeName: '演示外出',
    department: '研发中心',
    leaveType: null,
    overtimeTreatment: 'NOT_APPLICABLE',
    payrollCreditMinutes: 0,
    timeOffCreditMinutes: 0,
    recognizedWorkMinutes: 180,
    intervalStart: '2026-07-28T02:00:00Z',
    intervalEndExclusive: '2026-07-28T05:00:00Z',
  },
  {
    documentId: 'OA-DOC-DEMO-004',
    sourceDocumentId: '922337203685477580812349',
    sourceVersion: '1',
    documentType: 'TRIP',
    sourceStatus: 'APPROVED',
    effectiveCandidate: true,
    employeeNumber: 'SZ1003',
    employeeName: '演示出差',
    department: '职能中心',
    leaveType: null,
    overtimeTreatment: 'NOT_APPLICABLE',
    payrollCreditMinutes: 0,
    timeOffCreditMinutes: 0,
    recognizedWorkMinutes: 960,
    intervalStart: '2026-07-27T00:00:00Z',
    intervalEndExclusive: '2026-07-29T00:00:00Z',
  },
  {
    documentId: 'OA-DOC-DEMO-002',
    sourceDocumentId: '922337203685477580812347',
    sourceVersion: '2',
    documentType: 'UNKNOWN',
    sourceStatus: 'UNKNOWN',
    effectiveCandidate: false,
    employeeNumber: null,
    intervalStart: null,
    intervalEndExclusive: null,
  },
];

export const demoIntegrationStatus: IntegrationStatusView = {
  deliContractStub: 'PASS',
  oaContractStub: 'PASS',
  filePortContract: 'PASS',
  deliLive: 'NOT_VERIFIED',
  oaLive: 'NOT_VERIFIED',
  productionFileStorage: 'NOT_VERIFIED',
};
